/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.image.BufferedImage;
import java.awt.image.ImageObserver;
import java.io.File;
import java.io.IOException;
import java.text.AttributedCharacterIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sk.stu.fiit.controllers.EmployerController;
import sk.stu.fiit.exceptions.BlankFields;

/**
 *
 * @author jarni
 */
public class AddEmployer extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployer
     */
    
    MainWindow parent = new MainWindow();
    
    public AddEmployer(MainWindow parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        txfName = new javax.swing.JTextField();
        txfArea = new javax.swing.JTextField();
        txfNum = new javax.swing.JTextField();
        btnLogo = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlLogo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(390, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblHeading.setText("Pridanie zamestnávateľa");
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        lblName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblName.setText("Názov");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lblArea.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblArea.setText("Oblasť podnikania");
        getContentPane().add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblNum.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblNum.setText("Počet zamestnancov");
        getContentPane().add(lblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblLogo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblLogo.setText("Logo (150x150)");
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        getContentPane().add(txfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 330, -1));
        getContentPane().add(txfArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 330, -1));
        getContentPane().add(txfNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 330, -1));

        btnLogo.setText("Vybrať logo");
        btnLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogoMouseReleased(evt);
            }
        });
        getContentPane().add(btnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        btnAdd.setText("Pridať");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddMouseReleased(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        btnCancel.setText("Zrušiť");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        pnlLogo.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 70, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private EmployerController empCon = new EmployerController();
    private BufferedImage logo = null;
    
    private void btnLogoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoMouseReleased
        //ChooseLogo chooseLogo = new ChooseLogo(this);
        //chooseLogo.setVisible(true);
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG, JPG, PNG, BMP, GIF", "jpeg", "jpg", "png", "bmp", "gif");
        fileChooser.setFileFilter(filter);
        int value = fileChooser.showOpenDialog(this);
        if(value == JFileChooser.APPROVE_OPTION) {
            try {
                this.logo = ImageIO.read(fileChooser.getSelectedFile());
                System.out.println("Vyslo to");
                pnlLogo.getGraphics().drawImage(this.logo, 0, 0, 70, 70, this);
                
            } catch (IOException e) {
                System.out.println(e);
                System.out.println("Kdesi je chyba");
            }
        }
    }//GEN-LAST:event_btnLogoMouseReleased
    
    private void btnAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseReleased
        try {
            empCon.addEmployer(txfName.getText(), txfArea.getText(), txfNum.getText(), logo);
            parent.initEmpTables();
            dispose();
        } catch (BlankFields ex) {
            JOptionPane.showMessageDialog(rootPane, "Vyplňte všetky polia a vyberte logo.", "Nevyplnené údaje", JOptionPane.ERROR_MESSAGE);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Počet zamestnancov musí byť kladné celé číslo.", "Nesprávny formát", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAddMouseReleased

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        dispose();
    }//GEN-LAST:event_btnCancelMouseReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddEmployer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddEmployer().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogo;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNum;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JTextField txfArea;
    private javax.swing.JTextField txfName;
    private javax.swing.JTextField txfNum;
    // End of variables declaration//GEN-END:variables
}
