/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sk.stu.fiit.models.Employer;

/**
 *
 * @author jarni
 */
public class EmployerProfile extends javax.swing.JFrame {

    /**
     * Creates new form EmployerProfile
     */
    private BufferedImage logo;
    
    public EmployerProfile(Employer emp) {
        logo = emp.getLogo();
       
        initComponents();
        jLabel1.setIcon(new ImageIcon(logo));
        //this.logo = emp.getLogo();
        lblName.setText(emp.getName());
        lblArea.setText(emp.getArea());
        lblNum.setText(String.valueOf(emp.getNumEmployees()));
        //pnlLogo.getGraphics().drawLine(1, 1, 50, 50);
        /*pnlLogo.getGraphics().drawImage(emp.getLogo(), 0, 0, 50, 50, this);
        
        this.logo = emp.getLogo();
        drawIm();*/
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblAreaText = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblNumText = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Tesla");
        lblName.setToolTipText("");
        lblName.setMaximumSize(new java.awt.Dimension(47, 20));
        lblName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblNamePropertyChange(evt);
            }
        });
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        lblAreaText.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblAreaText.setText("Oblasť podnikania:");
        getContentPane().add(lblAreaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, -1));

        lblArea.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblArea.setText("OPX");
        getContentPane().add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        lblNumText.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblNumText.setText("Počet zamestnancov:");
        getContentPane().add(lblNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lblNum.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblNum.setText("X");
        getContentPane().add(lblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jButton1.setText("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 150, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        dispose();
    }//GEN-LAST:event_jButton1MouseReleased

    private void lblNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblNamePropertyChange
        System.out.println("Preco to do certa nejde");
        //drawIm();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNamePropertyChange

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EmployerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EmployerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EmployerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EmployerProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EmployerProfile().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblAreaText;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblNumText;
    // End of variables declaration//GEN-END:variables
}
