/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author jarni
 */
public class Pokus extends javax.swing.JPanel {

    /**
     * Creates new form Pokus
     */
    public Pokus() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics gp){
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("D:\\Skola/duplikacie.png"));
        } catch (IOException e) {
            System.out.println(e);
        }
        
        //gp.drawImage(img, 20, 20, this);
        
        gp.drawImage(img, 20, 20, 450, 450, this);
        /*gp.setColor(Color.YELLOW);
        gp.fillRect(50, 50, 640, 640);
        for(byte i=0;i<8;i++){
            for(byte j=0;j<8;j++){
                if((i+j)%2 == 0){
                    gp.setColor(Color.ORANGE);
                    gp.fillRect(j*80+50, i*80+50, 80, 80);
                }
            }
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
