/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.awt.Component;
import java.util.List;
import javax.swing.JFileChooser;

/**
 *
 * @author jarni
 */
public class Pokus2 extends javax.swing.JFrame {

    /**
     * Creates new form Pokus2
     */
    public Pokus2() {
        initComponents();
        //System.out.println(myFileChooser.getComponents());
        Component[] components = myFileChooser.getComponents();
        
        for (Component comp: components){
            System.out.println(comp.getClass());
        }
        
        int returnVal = myFileChooser.showOpenDialog(new MainWindow());
        /*if(returnVal == JFileChooser.APPROVE_OPTION) {
           System.out.println("You chose to open this file: " +
                myFileChooser.getSelectedFile().getName());
        }*/
        Pokus pokus = new Pokus();
        getContentPane().add(pokus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myFileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myFileChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                myFileChooserMouseReleased(evt);
            }
        });
        getContentPane().add(myFileChooser, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myFileChooserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myFileChooserMouseReleased
        System.out.println("nieco vypisem");        // TODO add your handling code here:
    }//GEN-LAST:event_myFileChooserMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pokus2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pokus2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pokus2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pokus2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pokus2().setVisible(true);
            }
        });
    }
    
    private void daco(){
        System.out.println(myFileChooser.getSelectedFile().getAbsolutePath());
        System.out.println(myFileChooser.getComponent(0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser myFileChooser;
    // End of variables declaration//GEN-END:variables
}
