/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sk.stu.fiit.controllers.LeaseController;
import sk.stu.fiit.data.Data;
import sk.stu.fiit.models.JobOffer;
import sk.stu.fiit.models.employees.Education;
import sk.stu.fiit.models.employees.Specialist;

/**
 *
 * @author jarni
 */
public class ShowOffer extends javax.swing.JFrame {

    /**
     * Creates new form ShowOffer
     */
    
    private List<Specialist> specs = new ArrayList<Specialist>();
    private JobOffer offer;
    private MainWindow parent;
    
    public ShowOffer(JobOffer offer, MainWindow parent) {
        initComponents();
        
        this.offer = offer;
        this.parent = parent;
        
        slblType.setText(offer.getType());
        
        if (offer.getNumEmp() == 1)
            slblDesc.setText("Spoločnosť " + offer.getEmployer().getName() + " hľadá do svojho tímu nového kolegu.");
        else
            slblDesc.setText("Spoločnosť " + offer.getEmployer().getName() + " hľadá do svojho tímu " + offer.getNumEmp() + " nových kolegov.");

        slblManDay.setText(String.valueOf(offer.getManDay()));
        slblEdu.setText(offer.getEducation().toString());
        slblExper.setText(String.valueOf(offer.getExperience()));
        if (Boolean.logicalOr(offer.getType().equals("Programátor") , offer.getType().equals("Administrátor"))){
            slblArea.setText(offer.getArea());
        }
        else if (offer.isNBU()){
            slblAreaOrNBU.setText("Je potrebné byť auditor kybernetickej bezpečnosti");
            slblArea.setVisible(false);
        }
        
        if (! offer.getType().equals("Administrátor"))
            lblPlatform.setVisible(false);
        else
            slblPlatform.setText(offer.getPlatform());
        
        for (String certificate : offer.getCertificates()) {
            JLabel lblNew = new JLabel();
            lblNew.setText(certificate);
            lblNew.setFont(new Font("sansserif", Font.PLAIN, 14));
            spnlCerts.add(lblNew);
        }
        
        for (Specialist spec : Data.getAllSpecialists()) {
            if (spec.goodForPosition(offer))
                specs.add(spec);
        }
        
        tblSpec.setModel(initSpecTableModel());
        
    }
    
    private TableModel initSpecTableModel(){
        List<String[]> values = new ArrayList<String[]>();
        List<String> columns = new ArrayList<String>();;
                  
        for (Specialist spec: specs){
            if (columns.isEmpty())
                columns = spec.columnsTable();
            if (spec.isFree())
                values.add(spec.rowsTable());
        }
        
        
        TableModel tableModel = new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray());
        return tableModel;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        slblDesc = new javax.swing.JLabel();
        slblType = new javax.swing.JLabel();
        lblManDay = new javax.swing.JLabel();
        slblPlatform = new javax.swing.JLabel();
        slblEdu = new javax.swing.JLabel();
        lblCertificates = new javax.swing.JLabel();
        slblAreaOrNBU = new javax.swing.JLabel();
        lblPlatform = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        slblManDay = new javax.swing.JLabel();
        lblEdu1 = new javax.swing.JLabel();
        spnlCerts = new javax.swing.JPanel();
        lblExper1 = new javax.swing.JLabel();
        slblExper = new javax.swing.JLabel();
        slblArea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpec = new javax.swing.JTable();
        lblManDay2 = new javax.swing.JLabel();
        lblManDay3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblHeading.setText("Pracovná ponuka");
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        slblDesc.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        slblDesc.setText("Spoločnosť ... hľadá do svojho tímu .. nových kolegov.");
        getContentPane().add(slblDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        slblType.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        slblType.setText("Typ špecialistu");
        getContentPane().add(slblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lblManDay.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        lblManDay.setText("Vyhovujúci špecialisti");
        getContentPane().add(lblManDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        slblPlatform.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        getContentPane().add(slblPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, -1, -1));

        slblEdu.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        slblEdu.setText("Najvyššie dosiahnuté vzdelanie");
        getContentPane().add(slblEdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        lblCertificates.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblCertificates.setText("Požadované certifikáty");
        getContentPane().add(lblCertificates, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        slblAreaOrNBU.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        slblAreaOrNBU.setText("Zaradenie:");
        getContentPane().add(slblAreaOrNBU, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        lblPlatform.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblPlatform.setText("Platforma:");
        lblPlatform.setVisible(false);
        getContentPane().add(lblPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        btnAdd.setText("Pridať špecialistov do prenájmu ");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddMouseReleased(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 720, -1, -1));

        btnCancel.setText("Zrušiť");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 760, -1, -1));

        slblManDay.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        slblManDay.setText("Odmena:");
        getContentPane().add(slblManDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        lblEdu1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblEdu1.setText("Minimálne vzdelanie");
        getContentPane().add(lblEdu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        spnlCerts.setLayout(new javax.swing.BoxLayout(spnlCerts, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(spnlCerts, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 290, 100));

        lblExper1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblExper1.setText("Dĺžka praxe:");
        getContentPane().add(lblExper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        slblExper.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        slblExper.setText("Dĺžka praxe");
        getContentPane().add(slblExper, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        slblArea.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        slblArea.setText("Dĺžka praxe");
        getContentPane().add(slblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        tblSpec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSpec.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tblSpec);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 460, 120));

        lblManDay2.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        lblManDay2.setText("Požiadavky");
        getContentPane().add(lblManDay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblManDay3.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        lblManDay3.setText("Odmena:");
        getContentPane().add(lblManDay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        dispose();
    }//GEN-LAST:event_btnCancelMouseReleased

    private void btnAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseReleased
        int[] specRows = tblSpec.getSelectedRows();
        
        if (specRows.length == 0){
            JOptionPane.showMessageDialog(rootPane, "Vyberte zamestnanca, ktorého chcete priradiť k pracovnej ponuke.", "Nie je vybraný zamestnanec", JOptionPane.ERROR_MESSAGE);
        }
        else if (specRows.length > offer.getNumEmp()){
            if (offer.getNumEmp() == 1)
                JOptionPane.showMessageDialog(rootPane, "Pozícia je iba pre 1 zamestnanca.", "Príliš veľa zamestnancov", JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(rootPane, "Pozícia je iba pre " + offer.getNumEmp() + "zamestnancov.", "Príliš veľa zamestnancov", JOptionPane.ERROR_MESSAGE);
        }
        else{
            List<Specialist> forLease = new ArrayList<Specialist>();
            for (int i = 0; i < specRows.length; i++) {
                forLease.add(specs.get(specRows[i]));
            }
            
            LeaseController leaCon = new LeaseController();
            leaCon.addLease(offer.getEmployer(), forLease);
            
            offer.setNumEmp(offer.getNumEmp() - specRows.length);
            if (offer.getNumEmp() == 1)
                slblDesc.setText("Spoločnosť " + offer.getEmployer().getName() + " hľadá do svojho tímu nového kolegu.");
            else
                slblDesc.setText("Spoločnosť " + offer.getEmployer().getName() + " hľadá do svojho tímu " + offer.getNumEmp() + " nových kolegov.");
            
            parent.initLeaseTable();
            parent.initSpecTables();
            tblSpec.setModel(initSpecTableModel());
                   
        }
        
    }//GEN-LAST:event_btnAddMouseReleased

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowOffer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowOffer().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCertificates;
    private javax.swing.JLabel lblEdu1;
    private javax.swing.JLabel lblExper1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblManDay;
    private javax.swing.JLabel lblManDay2;
    private javax.swing.JLabel lblManDay3;
    private javax.swing.JLabel lblPlatform;
    private javax.swing.JLabel slblArea;
    private javax.swing.JLabel slblAreaOrNBU;
    private javax.swing.JLabel slblDesc;
    private javax.swing.JLabel slblEdu;
    private javax.swing.JLabel slblExper;
    private javax.swing.JLabel slblManDay;
    private javax.swing.JLabel slblPlatform;
    private javax.swing.JLabel slblType;
    private javax.swing.JPanel spnlCerts;
    private javax.swing.JTable tblSpec;
    // End of variables declaration//GEN-END:variables
}
