/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sk.stu.fiit.models.Lease;
import sk.stu.fiit.models.employees.Specialist;

/**
 *
 * @author jarni
 */
public class ShowLease extends javax.swing.JFrame {

    /**
     * Creates new form ShowLease
     */
    public ShowLease(Lease lease) {
        initComponents();
        
        slblEmpl.setText(lease.getEmployer().getName());
        lblLogo.setIcon(new ImageIcon(lease.getEmployer().getLogo()));
        tblSpecs.setModel(initTableSpecs(lease.getSpecialists()));
    }
    
    private TableModel initTableSpecs(List<Specialist> specs ){
        List<String[]> values = new ArrayList<String[]>();
        List<String> columns = new ArrayList<String>();;
     
        for (Specialist spec: specs){
            values.add(new String[] {spec.getName(), spec.getType(), String.valueOf(spec.getManDay()), String.valueOf(spec.getExperience()), spec.getEducation().toString()});
        }
        columns.add("Meno");
        columns.add("Typ špecialistu");
        columns.add("Cena za deň");
        columns.add("Dĺžka praxe");
        columns.add("Vzdelanie");
        
        
        TableModel tableModel = new DefaultTableModel(values.toArray(new Object[][] {}), columns.toArray());
        return tableModel;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblSpecs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpecs = new javax.swing.JTable();
        slblEmpl = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 150, 150));

        lblSpecs.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblSpecs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpecs.setText("Špecialisti");
        lblSpecs.setToolTipText("");
        lblSpecs.setMaximumSize(new java.awt.Dimension(47, 20));
        getContentPane().add(lblSpecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        tblSpecs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSpecs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 530, 180));

        slblEmpl.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        slblEmpl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slblEmpl.setText("Tesla");
        slblEmpl.setToolTipText("");
        slblEmpl.setMaximumSize(new java.awt.Dimension(47, 20));
        getContentPane().add(slblEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOKMouseReleased(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseReleased
        dispose();
    }//GEN-LAST:event_btnOKMouseReleased

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowLease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowLease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowLease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowLease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowLease().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSpecs;
    private javax.swing.JLabel slblEmpl;
    private javax.swing.JTable tblSpecs;
    // End of variables declaration//GEN-END:variables
}
